using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks.Dataflow;
using System.Security.Cryptography;
using University.DotnetLabs.Lab4.TestClassGeneratorLibrary.Interfaces;
using University.DotnetLabs.Lab4.TestClassGeneratorLibrary.Configs;
using University.DotnetLabs.Lab4.TestClassGeneratorLibrary.Pipeline;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;

namespace University.DotnetLabs.Lab4.TestClassGeneratorLibrary.Pipeline.Tests;
[TestClass]
public class University_DotnetLabs_Lab4_TestClassGeneratorLibrary_Pipeline_Tests
{
    private TestPipeline _testPipeline;
    private Mock<ITestClassGenerator> _generator;
    [TestInitialize]
    public void TestInitialize()
    {
        _generator = new Mock<ITestClassGenerator>();
        PipelineConfigs configs = default;
        _testPipeline = new TestPipeline(_generator.Object, configs);
    }

    [TestCleanup]
    public void TestCleanup()
    {
    }

    [TestMethod]
    public void TestPipeline_Generate_Test()
    {
        string filePath = default;
        string outputFolder = default;
        var actual = TestPipeline.Generate(filePath, outputFolder);
        Task expected = default;
        Assert.AreEqual(actual, expected);
        Assert.Fail("autogenerated");
    }
}