using System.Collections.Concurrent;
using System.Diagnostics;
using University.DotnetLabs.Lab1.TracerLibrary.Exceptions;
using University.DotnetLabs.Lab1.TracerLibrary;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;

namespace University.DotnetLabs.Lab1.TracerLibrary.Tests;
[TestClass]
public class University_DotnetLabs_Lab1_TracerLibrary_Tests
{
    private Tracer _tracer;
    [TestInitialize]
    public void TestInitialize()
    {
        _tracer = new Tracer();
    }

    [TestCleanup]
    public void TestCleanup()
    {
    }

    [TestMethod]
    public void Tracer_GetTraceResult_Test()
    {
        var actual = Tracer.GetTraceResult();
        TraceResult expected = default;
        Assert.AreEqual(actual, expected);
        Assert.Fail("autogenerated");
    }

    [TestMethod]
    public void Tracer_StartTrace_Test()
    {
        Tracer.StartTrace();
        Assert.Fail("autogenerated");
    }

    [TestMethod]
    public void Tracer_StopTrace_Test()
    {
        Tracer.StopTrace();
        Assert.Fail("autogenerated");
    }
}